### ISSUE TITLE
Update certification criteria with L3 support requirements

### ISSUE THREAD

**Issue by arthurdm** [IBM/cp4apps-hub#6]
We need to define exactly what is needed from a certified stack in terms of L3 support - which could be an entry in a certain queue page, or an equivalent way to plug into the support flow.

**Comment by covener** [comment]
Here's my 2c:

The base principle is that every CP4A-entitled user (using "Accelerators for Teams" ratio) must be entitled to full commercial support by engaging (only) with IBM for every aspect of a certified stack.

"Every aspect" includes but is not limited to:
 - The final dev/runtime image which will usually be a close derivative of some existing image
 - Any scripts/etc used to create the final dev/runtime image
 - Any embedded pipeline definition
 - Any runtime or framework  or library used by the stack.

"Commercial support" means:
- customer support (L2)
- product support (L3)
   - Must include off-hours for critical situations
   - Should have director-level approval to understand the long-term commitment
   - Engineers performing the work must onboard into the support platform. 
       -  IBM-internal link to what that entails: https://github.ibm.com/IBMCloudPak4Apps/icpa-support/wiki/L3-onboarding
   - The identified team should be tightly integrated into the CP4APPS development/release process with respect to maintenance delivery vehicles, image scanning, other changes.

The requirements for L2 support by IBM for otherwise approved CP4A content is:
 - Skills Transfer Education from Development (coordinated with Swati K.) 
 - _One_ of the following for every aspect of the stack
    - An entry in https://ibm.biz/WASQueue detailing how L3 can be contacted in a formal support platform (such as the IBM Support Community)
    - An explicit, confirmed agreeement with another support or development organization to take escalations to what we'd call L3 
      - For example, if the runtime or framework are RHR content.

For example, if Stack X uses community images or a community binaries for their runtime, they would have to provide that support themselves or make arrangements to provide it. If they provide it themselves, they have to be able to fulfill it in a meaningful way (skills, upstream participation, etc).  A more ideal arrangement is to use RHOCP/RHR or closely related content (such as UBI images) where that aspect can be fulfilled by RedHat.

**Comment by arthurdm** [comment]
thanks @covener!   I incorporated these changes into the main doc.
